### ISSUE TITLE
Refactor data bags to attribtues

### ISSUE THREAD

**Issue by estahn** [SumoLogic/sumologic-collector-chef-cookbook#35]
https://coderanger.net/data-bags/

**Comment by Z3r0Sum** [comment]
@estahn Curious why you think separating data from code is a bad thing?  If I want to change data, its now tightly coupled with my chef code.  Personally, I don't want to have to worry about running through unit tests, to double-check I didn't screw something else up, in order to change Bob's shell from bash to zsh.  I can simply just push an update out to a data bag.  Thoughts?

**Comment by sumoway** [comment]
I'm trying to close out issues, but there doesn't seem to be a verdict on this one.  I'm going to close it out because what we have appears to be working without any major impact.  I'll keep it on the radar and re-open as necessary.
