### ISSUE TITLE
What happens when the log file is rotated ? 

### ISSUE THREAD

**Issue by dorongutman** [SumoLogic/sumologic-collector-chef-cookbook#82]
Do I need to restart the collector or send it a specific command/signal so it'll pick up the new file or does it detect it automatically ?

**Comment by duchatran** [comment]
@dorongutman: Please refer to this help (under How does Sumo Logic handle log file rotation) for more specifics: 
http://help.sumologic.com/Send_Data/Sources/Local_File_Source

Another key thing is the file path provided must match the rotated file pattern (otherwise collector won't even pickup the rotated files). For example, to continue the example, the pattern should be *.log*
